export default {
  Colors: {
    BACKGROUND: '#000000',
    BACKGROUND_GRADIENT_LIGHT: '#000000',
    BACKGROUND_GRADIENT_DARK: '#000000',
    FONT_COLOR: '#FFFF00',
    FONT_COLOR_LIGHT: '#FFFF00',
    ICON_COLOR: '#FFFF00',
    ICON_COLOR_HEADER: '#FFFF00',
  },

  Sizes: {
    FONTSIZE_INPUT: 18,
    FONTSIZE_SEARCH: 16,
    INPUT_SIZE: 20,
    ICON_SIZE: 20,
    ICON_SIZE_HEADER: 25,
  },
};
