export default {
  Colors: {
    BACKGROUND: '#000000',
    BACKGROUND_GRADIENT_LIGHT: '#333333',
    BACKGROUND_GRADIENT_DARK: '#333333',
    BUTTON_DISABLED: '#C3C3C3',
    FONT_COLOR: '#FFFFFF',
    FONT_COLOR_LIGHT: '#FFFF00',
    FONT_COLOR_CLICKABLE: '#FFFF00',
    ICON_COLOR: '#FFFF00',
    ICON_COLOR_HEADER: '#FFFF00',
    INPUT_TEXT_COLOR: '#FFFF00',
    PLACEHOLDER_INPUT_TEXT_COLOR: '#FFFF00',
    BORDER_COLOR_INPUT: '#FFFF00',
    BORDER_COLOR_BUTTON: '#FFFF00',
    ERROR_COLOR: '#FFFFFF',
    SEARCH_BAR_COLOR: '#333333',
  },

  Sizes: {
    FONTSIZE_INPUT: 18,
    FONTSIZE_SEARCH: 16,
    INPUT_SIZE: 20,
    ICON_SIZE: 20,
    ICON_SIZE_HEADER: 25,
  },
};
