export default {
  Colors: {
    BACKGROUND: '#F8F8FF',
    BACKGROUND_GRADIENT_LIGHT: '#F5851F',
    BACKGROUND_GRADIENT_DARK: '#F45D27',
    FONT_COLOR: '#000000',
    FONT_COLOR_LIGHT: '#FFFFFF',
    ICON_COLOR: '#F5851F',
    ICON_COLOR_HEADER: '#FFFFFF',
  },

  Sizes: {
    FONTSIZE_INPUT: 18,
    INPUT_SIZE: 20,
    ICON_SIZE: 20,
    ICON_SIZE_HEADER: 25,
  },
};
