export default {
  Colors: {
    BACKGROUND: '#F8F8FF',
    BACKGROUND_GRADIENT_LIGHT: '#F77062',
    BACKGROUND_GRADIENT_DARK: '#FE5196',
    BUTTON_DISABLED: '#C3C3C3',
    FONT_COLOR: '#000000',
    FONT_COLOR_LIGHT: '#FFFFFF',
    FONT_COLOR_CLICKABLE: '#2A52BE',
    ICON_COLOR: '#FE5196',
    ICON_COLOR_HEADER: '#FFFFFF',
    INPUT_TEXT_COLOR: '#000000',
    PLACEHOLDER_INPUT_TEXT_COLOR: '#696969',
    BORDER_COLOR_INPUT: '#FE5196',
    BORDER_COLOR_BUTTON: '#F8F8FF',
    ERROR_COLOR: '#C12126',
    SEARCH_BAR_COLOR: '#CDCDCD',
  },

  Sizes: {
    FONTSIZE_INPUT: 18,
    FONTSIZE_SEARCH: 16,
    INPUT_SIZE: 20,
    ICON_SIZE: 22,
    ICON_SIZE_HEADER: 25,
  },
};
